name: "Deploy"
on:
  workflow_dispatch:

permissions: # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-azure
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  infrastructure:
    runs-on: ubuntu-latest
    env:
        ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
        ARM_USE_OIDC: true
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./terraform_infrastructure
        run : terraform init -backend-config="backend.tfvars"

      - name: Terraform Plan
        working-directory: ./terraform_infrastructure
        run: terraform plan -input=false -out="tfplan"

      - name: Terraform Apply
        working-directory: ./terraform_infrastructure
        run: terraform apply -auto-approve "tfplan"
